import type { Skills } from "../types";

export const Studying: Skills = {
    id: 'currently',
    title: `What I'm Currently Working On`,
    description: `I'm always seeking out new challenges and opportunities to expand my skills and knowledge. Here's some of the things that keep me busy:`,
    skills: [
        'Typescript',
        'Javascript',
        'React',
        'NodeJS',
        'Svelte',
        'Restful APIs',
        'Serverless Functions',
        'NFTs/SFTs',
        'Solana',
        'Rust',
        'Vercel',
        'Railway',
        'Netlify',
        'Apache',
        'PostgreSQL',
        'MySQL',
        'MongoDB',
        'Data Sovereignty',
        'Astro',
        'NextJS',
        'SvelteKit',
        'SQL',
        'TailwindCSS',
        'Test-Driven Development',
        'Performance Optimization',
        'Observability Systems',
        'Mentoring',
        'Star Atlas',
        'SmartFS',
        'Agency In A Box',
    ],
};