import type { Skills } from "../types";

export const Studying: Skills = {
    id: 'currently',
    title: `What I'm Currently Working On`,
    description: `I'm always seeking out new challenges and opportunities to expand my skills and knowledge. Here's some of the things that keep me busy:`,
    skills: [
        'Typescript',
        'Javascript',
        'React',
        'NodeJS',
        'Svelte',
        'Pinescript',
        'Restful APIs',
        'Serverless Functions',
        'NFTs/SFTs',
        'Solana',
        'Apache',
        'PostgreSQL',
        'MySQL',
        'MongoDB',
        'MedusaJS',
        'AI',
        'Data Sovereignty',
        'TailwindCSS',
        'Test-Driven Development',
        'Optimization',
        'Observability',
        'Mentoring',
    ],
};